# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'brbr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for brbr
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'GoogleMaps'
end
